- name: create user
  ansible.builtin.user: 
    name: roboshop 

- name: recursivly remove app dir
  ansible.builtin.file:
    path: /app
    state: absent    

- name: create app directory newly
  ansible.builtin.file:
    path: /app
    state: directory

- name: "downloading {{component}} application"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp

- name: "unzip the {{component}} application"
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes     
