- name: "stop the {{component}}"
  ansible.builtin.service:
    name: "{{component}}"
    state: stopped

- name: remove old code
  ansible.builtin.file:
    path: /app/*
    state: absent  

- name: "downloading {{component}} application"
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp

- name: "unzip the {{component}} application"
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes    

- name: install dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app 

- name: "restart the {{component}}"  
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted
    enabled: true  
      