- name: setup mongo repo to instal mngodb client
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo        

- name: install mongodb shell
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present 

- name: "get the {{component}} count"
  ansible.builtin.command:  mongo --host mongodb.daws91.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: product_count
  when: component = "catalodue"

- name: "get the {{component}} count"
  ansible.builtin.command:  mongo --host mongodb.daws91.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
  register: user_count
  when: component == "user"


# - name: print the count
#   ansible.builtin.debug:
#     msg: "product count: {{product_count}}"

- name: load catalogue data
  ansible.builtin.command: mongo --host mongodb.daws91.online < /app/schema/catalogue.js
  when: component == "catalogue" and product_count.stdout == "0" # keep double quotes
  ignore_errors: true

- name: load catalogue data
  ansible.builtin.command: mongo --host mongodb.daws91.online < /app/schema/user.js
  when: component == "user" and user_count.stdout == "0" # keep double quotes  
  ignore_errors: true
